### ISSUE TITLE
React-native

### ISSUE THREAD

**Issue by c3budiman** [evo3cx/gunadarma-s2#18]
ka mau nanya kalau react-native android begitu, sistem nya sama tidak ya dengan react biasa yang menggunakan component gituh? soalnya saya cek dia belum ada folder component nya, jadi kita buat sendiri ya? terus kalau tanpa android studio bisa tidak ya? saya deploy pake expo. kalau mau belajar reactnative dimana ya yang enak?

**Comment by reza-putra** [comment]
iya kamu harus buat sendiri, Iya react-native ini hampir sama seperti ReactJS bedanya adalah bagaimana cara reactnative bekerja, ini saya qoute dari web nya

```
React-Native is a framework for developing Android & iOS applications which shares 80% - 90% of Javascript code.
While React.js is a parent Javascript library for developing web applications.

While you use tags like <View>, <Text> very frequently in React-Native, React.js uses web html tags like <div> <h1> <h2>, which are only synonyms in dictionary of web/mobile developments.

For React.js you need DOM for path rendering of html tags, while for mobile application: React-Native uses AppRegistry to register your app.

```

**Comment by reza-putra** [comment]
maaf baru balas, issue kamu baru saya baca

**Comment by c3budiman** [comment]
okay siap kak saya udah mencoba nya enak juga pake react kak terima kasih

**Comment by reza-putra** [comment]
Oke, sama sama
