### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by riajamilatun** [evo3cx/gunadarma-s2#19]
![capture](https://user-images.githubusercontent.com/35392360/36142453-be175636-10da-11e8-9387-bd63d822f0c0.PNG)

kak mau tanya itu gimana ngatasinya?
by @riosetyo

**Comment by reza-putra** [comment]
Nnti malam saya coba cek yah masih di kantor

**Comment by reza-putra** [comment]
itu line 5 ada `<<< HEAD` itu kamu hapus baris itu tidak di kenal oleh reactjs
