### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by abdulrojak288** [evo3cx/gunadarma-s2#38]
assalammualaikum kak , mau tanya apakah bisa kita memonitoring user aplikasi android contoh app bukalapak dll yg sama berdasarkan jumlah pengguna aktif dan tidak aktif apa bisa di ketahui jumlah usernya???

**Comment by reza-putra** [comment]
kalo di tanya bisa atau gak, ya bisa tergatung dari programmer nya handle activity user nya seperti apa.
